# Generated by Django 4.0.6 on 2022-07-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='course',
        ),
        migrations.AddField(
            model_name='college',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Form.course'),
        ),
        migrations.AlterField(
            model_name='university',
            name='college',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Form.college'),
        ),
    ]
